// <auto-generated />
using System;
using KUSYS.Database.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KUSYS.Database.Migrations
{
    [DbContext(typeof(KUSYSDbContext))]
    partial class KUSYSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KUSYS.Data.POCO.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = "CSI101",
                            CourseName = "Introduction to Computer Science"
                        },
                        new
                        {
                            CourseId = "CSI102",
                            CourseName = "Algorithms"
                        },
                        new
                        {
                            CourseId = "MAT101",
                            CourseName = "Calculus"
                        },
                        new
                        {
                            CourseId = "PHY101",
                            CourseName = "Physics"
                        });
                });

            modelBuilder.Entity("KUSYS.Data.POCO.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6ca5ed4-a6ac-4b8c-9304-2b4de4369cf2"),
                            BirthDate = new DateTime(1996, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fethi",
                            Lastname = "Tekyaygil",
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9967),
                            UserId = new Guid("76e7ad2a-a350-47f1-a74d-55b308f16055")
                        },
                        new
                        {
                            Id = new Guid("9993ac14-534a-4d37-8798-c9fb009f755f"),
                            BirthDate = new DateTime(1997, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Yasemin",
                            Lastname = "Özen",
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9976),
                            UserId = new Guid("154ef833-3f9d-47f5-9dff-2be71ba7590c")
                        },
                        new
                        {
                            Id = new Guid("a42ef0fb-4aad-47df-85ab-29837004da30"),
                            BirthDate = new DateTime(2008, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Taha",
                            Lastname = "Tekyaygil",
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9979),
                            UserId = new Guid("de0d7f96-b99c-49bd-9750-9dbedf8619da")
                        });
                });

            modelBuilder.Entity("KUSYS.Data.POCO.StudentCourses", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("f6ca5ed4-a6ac-4b8c-9304-2b4de4369cf2"),
                            CourseId = "CSI101",
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9974)
                        },
                        new
                        {
                            StudentId = new Guid("f6ca5ed4-a6ac-4b8c-9304-2b4de4369cf2"),
                            CourseId = "MAT101",
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9975)
                        },
                        new
                        {
                            StudentId = new Guid("9993ac14-534a-4d37-8798-c9fb009f755f"),
                            CourseId = "CSI102",
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9978)
                        },
                        new
                        {
                            StudentId = new Guid("a42ef0fb-4aad-47df-85ab-29837004da30"),
                            CourseId = "CSI101",
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9980)
                        },
                        new
                        {
                            StudentId = new Guid("a42ef0fb-4aad-47df-85ab-29837004da30"),
                            CourseId = "CSI102",
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9980)
                        },
                        new
                        {
                            StudentId = new Guid("a42ef0fb-4aad-47df-85ab-29837004da30"),
                            CourseId = "MAT101",
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9981)
                        });
                });

            modelBuilder.Entity("KUSYS.Data.POCO.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76e7ad2a-a350-47f1-a74d-55b308f16055"),
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9946),
                            Password = "fe230b6xtLrMo+Ab+HWdNI6hzsE=",
                            Role = 1,
                            Username = "fethitekyaygil"
                        },
                        new
                        {
                            Id = new Guid("154ef833-3f9d-47f5-9dff-2be71ba7590c"),
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9957),
                            Password = "0IFYCPfTeVTHCiS7fJmv+QgQFlk=",
                            Role = 0,
                            Username = "yaseminozen"
                        },
                        new
                        {
                            Id = new Guid("de0d7f96-b99c-49bd-9750-9dbedf8619da"),
                            ModifiedDate = new DateTime(2022, 11, 16, 15, 57, 24, 658, DateTimeKind.Local).AddTicks(9965),
                            Password = "VOL7WalKDWYMXYkBgtCPx1Etx44=",
                            Role = 0,
                            Username = "tahatekyaygil"
                        });
                });

            modelBuilder.Entity("KUSYS.Data.POCO.Student", b =>
                {
                    b.HasOne("KUSYS.Data.POCO.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("KUSYS.Data.POCO.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KUSYS.Data.POCO.StudentCourses", b =>
                {
                    b.HasOne("KUSYS.Data.POCO.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KUSYS.Data.POCO.Student", "Student")
                        .WithMany("Courses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("KUSYS.Data.POCO.Course", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("KUSYS.Data.POCO.Student", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("KUSYS.Data.POCO.User", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
